device: 'cuda:1'
model: 'identifier_model'
dataset: 'iam_word_merged_new'
seed: 123456
img_height: 64
finetune: false


training:
  dset_name: 'iam_word_merged_new'
  dset_split: 'test'
  epochs: 200
  lr_policy: 'linear'
  start_decay_epoch: 120
  n_epochs_decay: 80
  batch_size: 32
  # optimization:
  lr: 1.0e-3
  # sampling and saving
  print_iter_val: 20
  start_save_epoch_val: 20
  save_epoch_val: 4
  ckpt_dir: 'ckpts'
  n_class: 80
  sort_input: true
  resume: ~
  pretrained_backbone: '/mnt/workspace/caijunwang/models/HiGANplus/HiGANplus_lstm/HiGAN+/runs/merged_new_ocr_1/ckpts/best.pth'
  random_clip: true
  process_style: true
  frozen_backbone: true


valid:
  dset_split: 'test'
  batch_size: 256


StyBackbone:
  resolution: 16
  max_dim: 256
  in_channel: 1
  init: 'N02'
  dropout: 0.2
  norm: 'bn'


WidModel:
  n_writer: 224
  in_dim: 256
  init: 'none'
